### ISSUE TITLE
no changes made in working directory; no commit for Image Automation

### ISSUE THREAD

**Issue by shalineekaran** [fluxcd/image-automation-controller#793] opened 2024-11-20 11:21 UTC
Getting:
```
no changes made in working directory; no commit
```

_Originally posted by @rayterrill in https://github.com/fluxcd/image-automation-controller/issues/159#issuecomment-829471395_

**Comment by shalineekaran** [comment] 2024-11-20 11:22
@kingdonb

**Comment by shalineekaran** [comment] 2024-11-20 11:23
@rayterrill

**Comment by kingdonb** [comment] 2024-11-20 12:59
A starting point for debugging is in the old Flux v1 migration guide, Image Automation Troubleshooting:

https://fluxcd.io/flux/migration/flux-v1-automation-migration/#troubleshooting

If you wish to engage the community support for debugging your flux image automations, a better way is joining the CNCF slack and posting a thread in the #flux channel there. We have commercial as well as community support options documented here:

https://fluxcd.io/support/#getting-flux-support

See the sub-heading "Getting help from the Flux Community" there. If you solve your issue with these debugging guides, please remember to post the resolution here.

**Comment by makkes** [comment] 2024-11-20 13:36
Duplicate of #159. Please use Slack or GitHub Discussions for support requests.

**Closed by makkes** 2024-11-20 13:36 UTC
