### ISSUE TITLE
SSH could not read data: Error waiting on socket

### ISSUE THREAD

**Issue by pjbgf** [fluxcd/image-automation-controller#365] opened 2022-05-20 08:33 UTC
FluxCD version: 0.30.2

Output of `flux check`

```
► checking prerequisites
✔ Kubernetes 1.20.12+vmware.1 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.18.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.21.3
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.17.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.22.3
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.22.5
✔ all checks passed
```

Output of `flux version`
```
flux: v0.30.2
helm-controller: v0.18.2
image-automation-controller: v0.21.3
image-reflector-controller: v0.17.1
kustomize-controller: v0.22.3
notification-controller: v0.23.2
source-controller: v0.22.5
```

ImageUpdateAutomation not working, the image-automation-controller's logs  says:

```
{
   "level":"error",
   "ts":"2022-05-17T08:57:04.660Z",
   "logger":"controller.imageupdateautomation",
   "msg":"Reconciler error",
   "reconciler group":"image.toolkit.fluxcd.io",
   "reconciler kind":"ImageUpdateAutomation",
   "name":"redacted",
   "namespace":"flux-system",
   "error":"unable to clone 'ssh://git@redacted/redacted/redacted': SSH could not read data: Error waiting on socket"
}
```

It looks like cannot write back the changes.
Thanks for help.

_Originally posted by @kallaics in https://github.com/fluxcd/image-automation-controller/issues/159#issuecomment-1128623682_

**Comment by cbanciu667** [comment] 2022-05-20 14:05
Hi, 

After 2 weeks in which we no issue with this problem, now it surfaced again (probably due to increased activity from devs).

Kubernetes v1.22
FluxCD version v0.30.2
ImageAutomationController: v0.22.1
Git repository: 12MB, hosted in Bitbucket, usual FluxCD structure, nothing special like many objects etc.
Other specifics: 
- same SSH key and Bitbucket user are used for ~10 clusters 
- tried to randomise and/or to increase the timeout and the intervals for GitRepository and for ImageUpdateAutomation
- tried to add more resources to the ImageAutomationController POD
- the error is present right away after restarting the POD
- the issue is very random in nature

Logs on debug mode:
`{"level":"debug","ts":"2022-05-20T13:52:24.276Z","logger":"controller.imageupdateautomation","msg":"attempting to clone git repository","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","gitrepository":{"namespace":"flux-system","name":"flux-system"},"ref":{"branch":"master"},"working":"/tmp/flux-system-flux-system2825380238"}
{"level":"error","ts":"2022-05-20T13:52:27.534Z","msg":"unable to clone 'ssh://git@bitbucket.org/MyRepo/my-repo.git': SSH could not read data: Error waiting on socket","name":"flux-system","namespace":"flux-system","reconciler kind":"ImageUpdateAutomation","annotations":null,"error":"error","stacktrace":"github.com/fluxcd/pkg/runtime/events.(*Recorder).Eventf\n\tgithub.com/fluxcd/pkg/runtime@v0.14.2/events/recorder.go:113\ngithub.com/fluxcd/image-automation-controller/controllers.(*ImageUpdateAutomationReconciler).event\n\tgithub.com/fluxcd/image-automation-controller/controllers/imageupdateautomation_controller.go:868\ngithub.com/fluxcd/image-automation-controller/controllers.(*ImageUpdateAutomationReconciler).Reconcile.func1\n\tgithub.com/fluxcd/image-automation-controller/controllers/imageupdateautomation_controller.go:153\ngithub.com/fluxcd/image-automation-controller/controllers.(*ImageUpdateAutomationReconciler).Reconcile\n\tgithub.com/fluxcd/image-automation-controller/controllers/imageupdateautomation_controller.go:286\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"level":"debug","ts":"2022-05-20T13:52:27.535Z","logger":"events","msg":"Warning","object":{"kind":"ImageUpdateAutomation","namespace":"flux-system","name":"flux-system","uid":"5f2b3355-655d-4326-9232-8a39e297b5a7","apiVersion":"image.toolkit.fluxcd.io/v1beta1","resourceVersion":"10313295"},"reason":"error","message":"unable to clone 'ssh://git@bitbucket.org/MyRepo/my-repo.git': SSH could not read data: Error waiting on socket"}
{"level":"error","ts":"2022-05-20T13:52:27.572Z","logger":"controller.imageupdateautomation","msg":"Reconciler error","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","error":"unable to clone 'ssh://git@bitbucket.org/MyRepo/my-repo.git': SSH could not read data: Error waiting on socket","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"level":"debug","ts":"2022-05-20T13:54:03.572Z","logger":"controller.imageupdateautomation","msg":"fetching git repository","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","gitrepository":{"namespace":"flux-system","name":"flux-system"}}`

**Comment by pjbgf** [comment] 2022-05-27 22:19
@kallaics @cbanciu667 we have two new release candidates that further improves the reliability of both controllers. Please give it a try and let us know how you get on:

`ghcr.io/fluxcd/source-controller:rc-4b3e0f9a`
`ghcr.io/fluxcd/image-automation-controller:rc-48bcca59`

Overall this issues are intermittent and will be recovered from eventually. But the changes should further decrease the likelihood of them happening.

**Comment by cbanciu667** [comment] 2022-05-30 16:51
Hi,

We have new errors on our 12 clusters after updating to the new docker images:

`2022-05-30T04:58:13.273Z error ImageUpdateAutomation/flux-system.flux-system - Reconciler error cannot push non-fastforwardable reference
2022-05-30T05:09:29.429Z info ImageUpdateAutomation/flux-system.flux-system - pushed commit to origin
2022-05-30T05:25:58.273Z info ImageUpdateAutomation/flux-system.flux-system - pushed commit to origin
2022-05-30T05:27:11.970Z info ImageUpdateAutomation/flux-system.flux-system - pushed commit to origin
2022-05-30T08:01:20.231Z info ImageUpdateAutomation/flux-system.flux-system - pushed commit to origin
2022-05-30T11:22:32.328Z error ImageUpdateAutomation/flux-system.flux-system - Reconciler error cannot push non-fastforwardable reference
2022-05-30T13:54:14.043Z error ImageUpdateAutomation/flux-system.flux-system - Reconciler error cannot push non-fastforwardable reference
2022-05-30T14:56:52.223Z error ImageUpdateAutomation/flux-system.flux-system - Reconciler error unable to fetch-connect to remote &#39;ssh://git@bitbucket.org/Project/myrepo.git&#39;: ssh: handshake failed: EOF`

I don't know if this is something related to our git configuration or is again some bug in the controllers but as before the images are randomly updated, sometimes it take longer, sometime less.

Please advise.

Thanks.

**Comment by aryan9600** [comment] 2022-06-06 16:56
Hi @cbanciu667, flux2 `v0.31.0` has been released with a fix for this problem. Would you mind upgrading and sharing your findings here? Thanks!

**Comment by cbanciu667** [comment] 2022-06-07 04:34
Hey @aryan9600, I updated flux yesterday on all our clusters, did some test deployments, but since the update I could not find any error related to ImageAutomation. Looks much better. From my side this bug can be closed.

**Closed** 2022-06-07 08:33 UTC
Labels: bug
