### ISSUE TITLE
v0.10.0 Updates unsuccessful with both implementations

### ISSUE THREAD

**Issue by Robbilie** [fluxcd/image-automation-controller#176] opened 2021-06-02 10:43 UTC
I currently have 2 gitrepository resources in the cluster. they are both based on repos in a bitbucket server. they both sync perfectly fine.

about a week ago the flux version was updated and thus came 0.10.0 of the automation controller.

since then, the controller logs the following error:

go-git:

{"level":"error","ts":"2021-06-02T10:41:14.166Z","logger":"controller-runtime.manager.controller.imageupdateautomation","msg":"Reconciler error","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"demo","namespace":"services","error":"empty git-upload-pack given"}

libgit2:

{"level":"error","ts":"2021-06-02T09:06:04.731Z","logger":"controller-runtime.manager.controller.imageupdateautomation","msg":"Reconciler error","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"demo","namespace":"services","error":"unable to clone 'https://xxx/bb/scm/sulu/sulu_services_config', error: failed to connect to xxx: Operation timed out"}

any ideas where this comes from?

**Comment by stefanprodan** [comment] 2021-06-02 10:44
Duplicate of:  #172 

A fix will be delivered today

**Comment by squaremo** [comment] 2021-06-02 10:48
> Duplicate of: #172

I don't see a timeout when using libgit2 mentioned in #172.

**Comment by stefanprodan** [comment] 2021-06-02 10:55
@squaremo I guess that timeout is due to libgit2 not doing shallow cloning.

@Robbilie you can increase the timeout with `GitRepository.spec.timeout`, set it to something like 60s, I guess your repo is quite large.

**Comment by Robbilie** [comment] 2021-06-02 11:02
i just rolled back to 0.9.1 of the controller and apparently it doesnt work with it either, not sure how it ever worked

ill try the timeout :)

**Comment by Robbilie** [comment] 2021-06-02 11:19
The repo is actually quite small tbh, thats why im really confused. the bitbucket logs also show 200 status codes for all requests which is also weird…

**Comment by stefanprodan** [comment] 2021-06-02 11:29
@Robbilie there is a new image available that you could try: `ghcr.io/fluxcd/image-automation-controller:v0.10.1` this should fix the go-git bug. Please let me know if it works for you.

**Comment by Robbilie** [comment] 2021-06-02 11:35
i just tried libgit2 after i fixed a colleague having inserted the wrong update marker -.-

i now tried your new image, but it still throws the same error with go-git, libgit2 works though

**Comment by stefanprodan** [comment] 2021-06-02 11:43
@Robbilie can you please verify that the new image has been rolled out in your cluster please

**Comment by Robbilie** [comment] 2021-06-02 11:54
verified and retried with go-git, not working :(

can you explain or link, what the issues origin might be? maybe i can assist in analyzing then :)

PS: coming from a differnt projects documentation & support the past few days, i really appreciate your support here, amazing :)

**Comment by hiddeco** [comment] 2021-06-02 12:35
When you say it is not working with `v0.10.1`, does it give you the exact same error as stated at the top of this issue?

**Comment by Robbilie** [comment] 2021-06-02 12:56
{"level":"error","ts":"2021-06-02T11:51:55.845Z","logger":"controller-runtime.manager.controller.imageupdateautomation","msg":"Reconciler error","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"demo","namespace":"services","error":"empty git-upload-pack given"}

**Comment by stefanprodan** [comment] 2021-06-03 08:51
This should've been fixed in `image-automation-controller:v0.11.0`, it has been released as part of flux2 0.14.2

**Comment by Robbilie** [comment] 2021-06-04 13:48
confirmed working :)

**Closed** 2021-06-04 13:54 UTC
